---
# The variables file used by the playbooks in the dbservers group.
# These don't have to be explicitly imported by vars_files: they are auto-populated.

mysql_port: 3306
dbuser: hedgeserv
dbname: hedgeservdb
upassword: abc123